name: Wave-Based Deployment

on:
  push:
    branches:
      - main  # Trigger only on main branch pushes
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Test the project
        run: "bundle exec ruby *test*"

  deploy_dev:
    name: Deploy to Development
    needs: build  # Waits for Build to finish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev (Placeholder)
        run: echo "Deploying to Development..."

  test_dev:
    name: Test Development Environment
    needs: deploy_dev
    runs-on: ubuntu-latest
    steps:
      - name: Run Integration Tests on Dev (Placeholder)
        run: echo "Running tests against Development..."

        # 🔹 Manual Approval Before Staging Deployment
  approval_staging:
    name: Approval for Staging
    needs: test_dev
    runs-on: ubuntu-latest
    environment:
      name: staging  # Requires approval in GitHub UI
    steps:
      - name: Waiting for Approval
        run: echo "Waiting for staging approval..."
      - name: Generate GitHub Compare Link
        run: |
          BASE_BRANCH="main"
          echo "🔗 Compare changes: https://github.com/${{ github.repository }}/compare/${BASE_BRANCH}...${{ github.sha }}"

  deploy_staging:
    name: Deploy to Staging
    needs: approval_staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging..."

  test_staging:
    name: Test Staging
    needs: deploy_staging
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests on Staging
        run: echo "Running tests on Staging..."

  # 🔹 Manual Approval Before Production Deployment
  approval_production:
    name: Approval for Production
    needs: test_staging
    runs-on: ubuntu-latest
    environment:
      name: prod1  # Requires approval in GitHub UI
    steps:
      - name: Waiting for Approval
        run: echo "Waiting for production approval..."

  deploy_region_1:
    name: Deploy to Region 1
    needs: approval_production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Region 1
        run: echo "Deploying to Region 1..."

  deploy_region_2:
    name: Deploy to Region 2
    needs: deploy_region_1
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Region 2
        run: echo "Deploying to Region 2..."

  deploy_region_3:
    name: Deploy to Region 3
    needs: deploy_region_2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Region 3
        run: echo "Deploying to Region 3..."
